language: ruby
cache:
  bundler: true
  directories:
    - node_modules
rvm:
  - 2.5
services:
  - postgresql
  - xvfb
addons:
  chrome: stable
  apt:
    packages:
      - wkhtmltopdf
before_script:
  - npm install
  - psql -c 'create database "trainers-hub_test";' -U postgres
script:
  - bundle exec rubocop
  - $(npm bin)/sass-lint -vq
  - bundle exec rspec
